import type { Metadata } from 'next';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Suspense } from 'react';
import Loading from '@/component/ui/loading';
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Catcher',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <ToastContainer />
        <Suspense fallback={<Loading />}>
          <section className='w-full h-full '>{children}</section>
        </Suspense>
      </body>
    </html>
  );
}
