query CheckMe  {
  me {
    success
    message
  }
}

mutation Regularlogin($input: EmailAndPasswordLoginInput!) {
  emailAndPasswordLogin(input: $input) {
    data {
      token
    }
    success
    message
  }
}

mutation Register($input: RegisterInput!) {
  registerAs(input: $input) {
    data
    success
    message
  }
}
